title: USWDS Sandbox
baseurl: "/uswds-sandbox"
url: "https://pglevy.github.io"

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true

exclude:
  - assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - README.md
  - vendor
  - webpack.config.js
