name: Sync Fork

on:
  schedule:
    - cron: '0 0 1 * *' # Run every month
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: pglevy
          head: main
          base: master
